updated mz for version 0.34.9

diff --git a/good/mz/mz.SlackBuild b/good/mz/mz.SlackBuild
--- a/good/mz/mz.SlackBuild
+++ b/good/mz/mz.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Slackware build script for paramiko
+# Slackware build script for mz
 
 # Copyright 2008-2009 Heinz Wiesinger, Amsterdam, The Netherlands
 # All rights reserved.
@@ -22,8 +22,8 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PRGNAM=paramiko
-VERSION=1.7.5
+PRGNAM=mz
+VERSION=0.34.9
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
@@ -32,6 +32,17 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
+
+if [ "$ARCH" = "i486" ]; then
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+fi
 
 set -e
 
@@ -48,13 +59,33 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-python setup.py install --root=$PKG
+# we need to link to libssp to not fail because of -fstack-protector
+sed -i "s/pcap rt/pcap rt ssp/" src/CMakeLists.txt
 
-find $PKG | xargs file | grep "shared object" | grep ELF | \
-  cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+cmake \
+  -DCMAKE_C_FLAGS="$SLKCFLAGS" \
+  -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
+  -DCMAKE_INSTALL_PREFIX=/usr \
+  -DLIB_SUFFIX="$LIBDIRSUFFIX" \
+  .
+
+make
+make install DESTDIR=$PKG
+
+mv $PKG/usr/share/man $PKG/usr/
+( cd $PKG/usr/man
+  find . -type f -exec gzip -9 {} \;
+  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+)
+
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a LICENSE PKG-INFO README docs $PKG/usr/doc/$PRGNAM-$VERSION
+mv $PKG/usr/share/doc/mz/* $PKG/usr/doc/$PRGNAM-$VERSION/
+rm -rf $PKG/usr/share
+cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README \
+  $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
